// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_5x9QQ6__HZGbdKhmDEQPZT28CcAVYBs',
    appId: '1:790906588205:web:64f9a3f7f9004b19923ca4',
    messagingSenderId: '790906588205',
    projectId: 'yavirac-d0090',
    authDomain: 'yavirac-d0090.firebaseapp.com',
    storageBucket: 'yavirac-d0090.firebasestorage.app',
    measurementId: 'G-6GY92Z3K4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYqZHJ6w_sgFFdaS5J3dFRvhY9OcYzME',
    appId: '1:790906588205:android:db2405d33df28efd923ca4',
    messagingSenderId: '790906588205',
    projectId: 'yavirac-d0090',
    storageBucket: 'yavirac-d0090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHfokftQ6apCrn7cA-i1noJhqhSUJE1Do',
    appId: '1:790906588205:ios:3951092338c9f2e7923ca4',
    messagingSenderId: '790906588205',
    projectId: 'yavirac-d0090',
    storageBucket: 'yavirac-d0090.firebasestorage.app',
    iosBundleId: 'com.example.baseDeDatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHfokftQ6apCrn7cA-i1noJhqhSUJE1Do',
    appId: '1:790906588205:ios:3951092338c9f2e7923ca4',
    messagingSenderId: '790906588205',
    projectId: 'yavirac-d0090',
    storageBucket: 'yavirac-d0090.firebasestorage.app',
    iosBundleId: 'com.example.baseDeDatos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_5x9QQ6__HZGbdKhmDEQPZT28CcAVYBs',
    appId: '1:790906588205:web:91aebe336333535b923ca4',
    messagingSenderId: '790906588205',
    projectId: 'yavirac-d0090',
    authDomain: 'yavirac-d0090.firebaseapp.com',
    storageBucket: 'yavirac-d0090.firebasestorage.app',
    measurementId: 'G-HM2D96LN3R',
  );
}
